version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "panmau"
    assignees:
      - "panmau"
    labels:
      - "Type: Maintenance"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "panmau"
    assignees:
      - "panmau"
    labels:
      - "Type: Maintenance"
