language: node_js
node_js:
  - "9"
  - "10"
script:
  - yarn global add codecov
  - yarn test
  - yarn build
after_success:
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
notifications:
  email: false
  webhooks: https://www.travisbuddy.com/?insertMode=update
