language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install codecov -g
  - npm test
  - npm run build
after_success:
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
